### ISSUE TITLE
APEX LEGENDSのトラッカーサイトから現在のランクポイントを取得する

### ISSUE THREAD

**Issue by stillmitsushige** [pistachiostudio/takohachi#12]
仕様 @stillmitsushige 
コーディング @quojama 

- !!tracker {platform} {username}でそのプレイヤーのランクポイントをdiscrodに出力する
- Discord上のIDとAPEX LEGENDSのIDは一致しないため別途DBに[Discord]と[APEX]のIDを紐付けるコマンドを用意する
- !!trackeradd @username [APEX ID]

**Comment by zztkm** [comment]
設計:

実装するコマンド
- `!! tracker add {platform} {username}`
    - tracking するユーザーを管理するスプレッドシートに追加
    - 列情報
        - A: Discord user id
        - B: platform
        - C: apex user name

- `!! tracker rankpoint`(スプレッドシートに登録済)
    - コマンドを実行したDiscordユーザーと紐づくApexユーザーのランクポイントをDiscordに出力する

**Comment by zztkm** [comment]
一応作った。

**Comment by quojama** [comment]
実装ed by @zztkm. nice work!
