### ISSUE TITLE
on_raw_reaction_addでERRORログがでる問題の修正

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#121]
- [/src/cogs/play.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/play.py)
- [/src/cogs/card_count.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/card_count.py)

にてon_raw_reaction_addイベント (絵文字でリアクションされた) があったら毎回セットで下記のERRORが記録される。

play.pyの方はあまり意味もわからず使っているglobal変数が関係している気がしているがどうなんだろう。

tkmに確認しつつログが出ないようにしたい。なにかわかることがあれば教えて下さい。

ちなみにBotの動作は問題ない感じだけどものすごく気持ち悪いので直したい

```python
2023-02-02 02:24:17 ERROR discord.client Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(args, **kwargs)
  File "/app/cogs/play.py", line 67, in on_raw_reaction_add
    if react_msg_id == message_id:
                       ^^^^^^^^^^
NameError: name 'message_id' is not defined



2023-02-02 02:24:17 ERROR discord.client Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(args, **kwargs)
  File "/app/cogs/card_count.py", line 136, in on_raw_reaction_add
    worksheet.sort((5, 'des'))
    ^^^^^^^^^

UnboundLocalError: cannot access local variable 'worksheet' where it is not associated with a value
```

**Comment by zztkm** [comment]
@quojama 

## [/src/cogs/play.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/play.py) について

- `on_raw_reaction_add` はリアクション全部に反応する
- play コマンドで global message_id が定義される前に reaction に反応してしまったからエラッた

## [/src/cogs/card_count.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/card_count.py)

- https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/card_count.py#L36 のブロック内に入れないといけないのでは？

**Comment by quojama** [comment]
@zztkm 

ありがとう色々試したりやってみた結果、

## [/src/cogs/play.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/play.py) について

これはまあそうで、そもそもmesasge_idが定義されるのはplayコマンドが走ってからなので、これが走ったあとじゃなければmessage_idは定義されてないという感じ。

これは設計から見直す必要がある気がしていて一旦保留する。

## [/src/cogs/card_count.py](https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/card_count.py)

これは

https://github.com/pistachiostudio/takohachi/blob/main/src/cogs/card_count.py#L36

の記述を

```python
if str(payload.emoji) in count_list:
```
から
```python
if str(payload.emoji) not in count_list:
    return
else:
```
と逆にしたらエラーが出なくなった。

**Comment by zztkm** [comment]
たしかにそれならエラーは出ないすね🤔

**Comment by quojama** [comment]
なぜかはあまり理解できていないが、「下まで行く前に早めに return で処理切り上げたろ」と思ってやってみたらエラーは出なかった

**Comment by zztkm** [comment]
ケースを考えてみると理解できると思いますよ 🌮 

以前のコードでは、`count_list` に含まれているかどうかに関わらず、`worksheet.sort((5, 'des'))` が 実行されていたが

今のコードでは、`count_list` に含まれていなければ return、それ以外は全て worksheet を開く処理が実行されるからだと思います

**Comment by quojama** [comment]
一旦おつかれ
