### ISSUE TITLE
毎朝みんなのValorantのランクをお知らせする

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#178]
## 概要

DBに登録された情報から毎朝APIを叩き、ランクの情報をお知らせします。

登録は各自がコマンドで行い、登録された人のみが発表されます。

## イメージ

たこ八からの投稿はこのような感じをイメージしています。

```
@助六弁当 Gold 1 (54) +13 ⤴
@茂林 Gold 1 (23) +24 ⤴
@おせち Immortal 2 (5) +32 ⤴
@芋 Diamond 3 (65) -29⤵
```

## API

[Henrik\-3/unofficial\-valorant\-api: Unofficial VALORANT API using the VALORANT Ingame API](https://github.com/Henrik-3/unofficial-valorant-api)

## DB

SQLiteで新しいテーブルを作る予定。

| ~~discord ID~~ | puuid | region | name | tag | yesterday_elo |
| --- | --- | --- | --- | --- | --- |
| ~~902384579238475~~ | 293489023405982345 | ap | 植 物 | help | 145 |

RiotのPUUIDを使ってAPIを呼び出すことで名前が変わっても大丈夫🙆‍♂

## 利用登録方法 (DBへの登録)

`/vradd [name] [tagline]` のようなコマンドで登録する。これでpuuidも~~discord id~~も取れる。

~~ただしこれだと本人以外も登録できる問題はある。そこを制御する方法はなさそう。~~

※discord IDとpuuidを連携することはやめた。

## かんたん設計

1. 朝7時にトリガー発火
2. puuidで一つずつAPIを叩き、情報を取る。
3. DBのyesterdayカラムと比較し、出力
4. name、tag、yesterdayカラムをそれぞれ今日のものに更新する
5. 投稿する

**Comment by stillmitsushige** [comment]
LGTM

**Comment by zztkm** [comment]
良さそうです

**Comment by quojama** [comment]
考えた結果discordのIDとの紐づけは行わないことにする。よってdiscord IDは取得しない
