### ISSUE TITLE
/apexrank コマンドを排除

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#209]
## 理由

- 現状動いておらず、担当者のモチベーションがないため

## やり方

- src/main.pyの48行目をコメントアウトする
    - ここ https://github.com/pistachiostudio/takohachi/blob/cb71724bd0d95efa538214cd246117b4e7b74703/src/main.py#L48C13-L48C33

**Comment by zztkm** [comment]
直し方（多分

api トークンを発行し直す
