### ISSUE TITLE
Spotify関連コマンド

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#21]
#### `!!sp 鈴木真海子 空耳`
- [ ] Search for an Item (`type=track`) ※typeはrequiredっぽい
  -  [x] trackの結果を返す。takohachiからはその曲のキーやラウドネス、popularityなどの情報を投稿する。
  -  [ ] パラメータはSpotifyの曲のURLやURIでもいけるようにしたい。（idがわかっているこの場合は別のメソッド）
      -  [ ] `!!sp https://open.spotify.com/track/6lbDeOzLyBSnUGk3QQturj?si=b0bc0ecdd1d34b53`
      -  [ ] `!!sp 6lbDeOzLyBSnUGk3QQturj`
  -  [ ] もし曲のURLやURIではなく、アルバムやアーティストのURLであった場合でも結果を返すようにしたい。

#### `!!spartist 鈴木真海子`
-  [x] Search for an Item (`type=artist`)
  -  [x] artistの結果を返す。takohachiからはそのアーティストのpopularity、ジャンル、関連アーティストなどの情報を投稿する。
  -  [ ] artistのURLやURIでもいけるようにしたい

#### `!!spalbum 鈴木真海子 ms`
-  [ ] Search for an Item (`type=album`)
  - [ ] albumの結果を返す。takohachiからはそのアルバムのpopularity、ジャンル、などの情報を投稿する。
  -  [ ] albumのURLやURIでもいけるようにしたい

#### かくにん
- [x] Space区切りのパラメータをひとかたまりとする方法を確認する！
- [x] 曲によってはアーティストやジャンルが複数名ある場合があるので、あるだけ返したい。
    -  [x] `鈴木真海子  金木犀` で検索するとArtist nameは`TOSHIKI HAYASHI(%C)` `鈴木真海子` の二つがある。その2つをゲットして、`Artist: TOSHIKI HAYASHI(%C), 鈴木真海子` としたい。

#### ライブラリ
  - spotipy https://spotipy.readthedocs.io/en/2.19.0/

#### 公式リファレンス
  - https://developer.spotify.com/documentation/web-api/reference/

**Comment by zztkm** [comment]
@quojama 開発完了していたらCloseお願いします！

**Comment by quojama** [comment]
こちらまだ継続中となります！
