### ISSUE TITLE
TCの一番古いチャットへのリンク表示コマンド

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#22]
思いつきメモ

朝起きたとき、しばらくDiscordを見てなかったときなど、溜まった未読を一番上から見たいとき、  
現状の使用ではスクロールして上までいかなければならず、未読が多いとかなり面倒。

`!!top` コマンドで、コマンドが書き込まれたテキストチャンネルの一番古いチャットのURLをgetし、embedで

タコ八:  【Go to top on this channel】

みたいなテキストリンクが投稿され、クリックすると一番上までひとっ飛びできる。  
このタコ八の書き込みは5-10秒くらいで消えるようにする。

- 特定のテキストチャンネルの**一番古い書き込みのURL**取れるのか？
- 理想は**コマンドを打った人の未読部分の一番古い投稿のURL**をgetできればかなり理想

これは結構便利そうだ

**Comment by zztkm** [comment]
@quojama チャット自体は取れそうです
https://stackoverflow.com/questions/67154885/how-to-get-the-first-message-in-a-channel

**Comment by zztkm** [comment]
discord.py 公式リファレンス

https://discordpy.readthedocs.io/ja/latest/api.html?highlight=text#discord.TextChannel.history

**Comment by quojama** [comment]
これがいいかな。ボタンもできるのかーー
https://discord.com/developers/docs/interactions/message-components#buttons

**Comment by zztkm** [comment]
やるかー

**Comment by quojama** [comment]
オッ.
インタラクションボタン実装 👀

**Comment by zztkm** [comment]
それは自分でやってください...

**Comment by quojama** [comment]
検討します

**Comment by zztkm** [comment]
UI Kit Button

https://discordpy.readthedocs.io/ja/latest/interactions/api.html#discord.ui.Button
