### ISSUE TITLE
VC mp3再生をもっといい感じに

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#34]
## やりたいこと (とりあえずローカルでのはなし)
- VCに入った状態で`!!play`コマンドを打つ
- ./mp3ディレクトリにあるファイルのリスト一覧を取得
- その上で下記のような書き込みを返す
```
どのmp3を再生しますか？
1️⃣ test.mp3
2️⃣ hello.mp3
3️⃣ brother.mp3
4️⃣ love.mp3
--
1️⃣ 2️⃣ 3️⃣ 4️⃣ 🔚 (これはリアクション)
```
- 例えば 2️⃣ をリアクションするとVCに入ってきて hello.mp3を再生する

## 現状
```python
mp3list = glob.glob('mp3/*')
mp3list = '\n'.join(mp3list)
await ctx.send(f"{mp3list}")
```
これで一つの投稿で/mp3ディレクトリのファイルが1つの書き込みで縦に改行されて出力はされた。  
```
mp3\test.mp3
mp3\hello.mp3
mp3\brother.mp3
mp3\love.mp3
```

## 課題
- `mp3\`の文字列をとりたい
- mp3の数に合わせて1️⃣... の絵文字を頭につけて投稿 (lenとかを使うのか？)
- 更にその数に合わせてメッセージに個数分の連番絵文字のリアクションをつける
- その絵文字に応じて再生するmp3を変える

## これはできてる
- VCに入ったり、抜けたり、mp3を再生したりするコードは出来ている

**Comment by zztkm** [comment]
課題について

## mp3\の文字列をとりたい**
- pathlib とか使うと良いです
- https://note.nkmk.me/python-pathlib-name-suffix-parent/

 ## mp3の数に合わせて1️⃣... の絵文字を頭につけて投稿 (lenとかを使うのか？)
- 絵文字の名前 `:emoji_1:`みたいな共通した名前ならその連番で format してやればOK
- f":emoji_{index_number}:" みたいな感じ

## 上記以外
- discord.py のリファレンスを読まんとわからんけど、できるとは思います
- 絵文字のリアションに応じては、cogs/save_image.py と同じ要領でいけると思います

**Comment by quojama** [comment]
かなり進んだ。あとはffmpeg

**Comment by quojama** [comment]
一応実装済
