### ISSUE TITLE
通貨機能[WIP]

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#42]
# 通貨機能

ピスタチオゲームのDiscordサーバーで機能させる遊びの通貨機能。  
[一応形はできている](https://github.com/pistachiostudio/takohachi/blob/master/cogs/currency.py)がスラッシュコマンドに対応してからリリースしたいかも。

## DBサンプル

| author          | author.id          | bonus | credit |
| --------------- | ------------------ | ----- | ------ |
| guojama#0001    | 538992968254619649 | 1     | 3000   |
| TSUNEDA#5170    | 292231231146426368 | 0     | 300    |
| mitsushige#1766 | 398085064438841358 | 1     | 4500   |

## bonus

無条件で全員に3,000pisを与えてdbに保存することも考えたが、サーバー参加時に無条件でauthor.idを保存することは規約にふれる可能性があるためやめることにした。

そのため、希望者のみ絵文字のリアクションで最初の所持金3,000pisを付与し、bonusフラグに1を立てる。流れは下記の通りになるかと思う。

- [x] 1. 絵文字リアクションがある
- [x] 1. 該当ユーザーのauthor.idがdbにない場合は無条件で追加し、creditを3,000、bonusを1とし、登録メッセージを返す
- [x] 1. 該当ユーザがすでにdbにある場合はbonusフラグをチェック
    - [x] i. 0の場合はdbに追加しcreditを3,000とし、bonusフラグを立て、メッセージを返す
    - [x] ii. 1の場合はすでにボーナス取得済なのでエラーを返す
    
    
    
    
    

## `!!pay [amout] [@user]`

- [x] コマンド送信者から[@user]へ[amount]pis支払う
  - [x] 送信者から-amount, [@user]へ+amount
- [x] コマンド送信者のamountが負になる場合はエラー
- [x] amountが数字でない場合はエラー
- [x] 受け取り者がdbに無い新規ユーザーの場合は登録。bonusフラグは0とする。

    

## `!!wallet`

- [x] コマンド送信者の現在の所持金をレスポンス

    

## `!!wallet [@user]`

- [x] [@user]の現在の所持金をレスポンス
  -  他人の財布の中身を覗けるのはどうなんだろう

    

## `on_member_join`

- [ ] ユーザーのサーバー参加時に自動で定額を付与
  - サーバー参加者のIDをすべて保存するのはちょっと抵抗があるので保留。

    

## `on_member_leave`

- [ ] これは何もしない。そのままデータは残しておく

    

## `!!rich`

- [x] 金持ちランキングを表示

    

## `!!shop`

- [x] 購入可能アイテムと金額の一覧がでる
- [ ] 売り切れ処理 

    

## `!!buy [item_name]`

- [x] コマンド送信者からitemの値段をマイナス
- [x] 購入したというメッセージを送信
  - CBSのCD、ロールなど？

**Comment by quojama** [comment]
カレー

**Comment by zztkm** [comment]
この規模だったら別のBOTとして起動しても良いレベルっすね

たこ八が働きすぎです

**Comment by quojama** [comment]
@zztkm それはちょっと気になってた。負荷がどれくらいでどれくらいというのが全くわからない。

**Comment by zztkm** [comment]
@quojama いうて現状でも動作の遅延が見られるとかはないんで動くとは思うので困ったら分離するくらいでもいいかもしれません
