### ISSUE TITLE
ローカル(windows)とUbuntuでglobの並び順が違う？

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/takohachi#93]
該当の.pyファイル (33行目あたりから)  
https://github.com/pistachiostudio/takohachi/blob/master/cogs/play.py

## 困った問題

`!!play` コマンドで、mp3ディレクトリの中のファイルをglobするが、Dockerコンテナ内のローカルと本番環境のUbuntuで並び順が違う。

Ubuntu側で何かしらやることがあるのかな？

## Windows (ローカル)
意図した並び順になっている。

![スクリーンショット 2022-12-25 035052](https://user-images.githubusercontent.com/4445606/209448301-54452346-890c-4106-bf7a-b7b51abfd3fc.png)

## 本番環境Ubuntu (Lightsail)
およよ！？毎回この並び順になる

![スクリーンショット 2022-12-25 035255](https://user-images.githubusercontent.com/4445606/209448316-c4b24a0e-81cc-43e8-962f-41373a65e43b.png)

**Comment by zztkm** [comment]
@quojama そもそも glob が返す内容は任意の順番なので、返ってきたリストをソートする処理を挟むのが良いと思います。

ソートしちゃえば結果は同じになります 👍🏼 

https://docs.python.org/ja/3/library/glob.html

**Comment by quojama** [comment]
そうなのかよ！
ソートを入れたいと思います。ブランチ切るか🫡

**Comment by quojama** [comment]
超簡単だったのでブランチ切るのめんどくさくてmasterへプッシュした
